[package]
name = "netwatch"
version = "0.3.0"
readme = "README.md"
description = "Cross-platform monitoring for network interface changes"
license = "MIT OR Apache-2.0"
authors = ["n0 team"]
repository = "https://github.com/n0-computer/net-tools"
keywords = ["networking", "interfaces"]
edition = "2021"

# Sadly this also needs to be updated in .github/workflows/ci.yml
rust-version = "1.81"

[lints]
workspace = true

[dependencies]
atomic-waker = "1.1.2"
bytes = "1.7"
n0-future = "0.1.1"
thiserror = "2"
time = "0.3.20"
tokio = { version = "1", features = [
    "io-util",
    "macros",
    "sync",
    "time",
] }
tokio-util = { version = "0.7", features = ["rt"] }
tracing = "0.1"

# non-browser dependencies
[target.'cfg(not(all(target_family = "wasm", target_os = "unknown")))'.dependencies]
quinn-udp = { package = "iroh-quinn-udp", version = "0.5.5" }
libc = "0.2.139"
netdev = "0.31.0"
socket2 = "0.5.3"
tokio = { version = "1", features = [
    "io-util",
    "macros",
    "sync",
    "rt",
    "net",
    "fs",
    "io-std",
    "signal",
    "process",
    "time",
] }

[target.'cfg(all(target_os = "linux", not(target_os = "android")))'.dependencies]
netlink-packet-core = "0.7.0"
netlink-packet-route = "0.19" # 0.20/21 is blocked on rtnetlink bumping its dependency
netlink-sys = "0.8.6"
rtnetlink = "=0.14.1" # pinned because of https://github.com/rust-netlink/rtnetlink/issues/83

[target.'cfg(target_os = "android")'.dependencies]
netlink-packet-core = "0.7.0"
netlink-packet-route = "0.19" # 0.20/21 is blocked on rtnetlink bumping its dependency
netlink-sys = "0.8.6"
rtnetlink = "=0.13.1" # pinned because of https://github.com/rust-netlink/rtnetlink/issues/83

[target.'cfg(target_os = "windows")'.dependencies]
wmi = "0.14"
windows = { version = "0.59", features = ["Win32_NetworkManagement_IpHelper", "Win32_Foundation", "Win32_NetworkManagement_Ndis", "Win32_Networking_WinSock"] }
windows-result = "0.3"
serde = { version = "1", features = ["derive"] }
derive_more = { version = "1.0.0", features = ["debug"] }

[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dependencies]
js-sys = "0.3"
web-sys = { version = "0.3", features = ["EventListener", "EventTarget"] }

[dev-dependencies]
testresult = "0.4.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# *non*-wasm-in-browser test/dev dependencies
[target.'cfg(not(all(target_family = "wasm", target_os = "unknown")))'.dev-dependencies]
tokio = { version = "1", features = [
    "io-util",
    "sync",
    "rt",
    "net",
    "fs",
    "macros",
    "time",
    "test-util",
] }

# wasm-in-browser test/dev dependencies
[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dev-dependencies]
tracing-subscriber-wasm = "0.1.0"
wasm-bindgen-test = "0.3"

[build-dependencies]
cfg_aliases = { version = "0.2" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "iroh_docsrs"]
